export const toys = [
    {
        id:1,
        name:"Ball Toy",
        image:require('./assets/ballToy.jpg'),
        desc:"Your pet will love this toy.",
        price:"200",
        paws:4,
    },
    {
        id:2,
        name:"Croco Toy",
        image:require('./assets/crocToy.jpg'),
        desc:"Your pet will love this toy.",
        price:"400",
        paws:4.3,
    },
    {
        id:3,
        name:"Bone Toy",
        image:require('./assets/boneToy.webp'),
        desc:"Your pet will love this toy.",
        price:"300",
        paws:4.5,
    },
    {
        id:4,
        name:"Dino Toy",
        image:require('./assets/dinoToy.jpg'),
        desc:"Your pet will love this toy.",
        price:"500",
        paws:4.4,
    },
    {
        id:5,
        name:"Duck Toy",
        image:require('./assets/duckToy.jpg'),
        desc:"Your pet will love this toy.",
        price:"500",
        paws:4.4,
    },
    {
        id:6,
        name:"Toy",
        image:require('./assets/someToy.jpg'),
        desc:"Your pet will love this toy.",
        price:"250",
        paws:3.9,
    },
]

export const food = [
    {
        id:1,
        name:"Himalaya Pet Food",
        image:require('./assets/petFood1.jpg'),
        desc:"Your pet will love this Food.",
        price:"1250",
        paws:4.3,
    },
    {
        id:2,
        name:"Canine Creek",
        image:require('./assets/petFood2.jpg'),
        desc:"Your pet will love this Food.",
        price:"1050",
        paws:4.5,
    },
    {
        id:3,
        name:"Peanut Butter",
        image:require('./assets/petFood3.jpeg'),
        desc:"Your pet will love this Food.",
        price:"950",
        paws:4.1,
    },
    {
        id:4,
        name:"Royal Pet Food",
        image:require('./assets/petFood4.jpg'),
        desc:"Your pet will love this Food.",
        price:"2250",
        paws:4.6,
    },
]