export const toys = [
    {
        id:1,
        name:"Ball Toy",
        image:require('./assets/ballToy.jpg'),
        desc:"A perfect toy designed scientifically for your furred one's.",
        price:200,
        paws:4,
    },
    {
        id:2,
        name:"Croco Toy",
        image:require('./assets/crocToy.jpg'),
        desc:"Your pet will love this toy.",
        price:400,
        paws:4.3,
    },
    {
        id:3,
        name:"Bone Toy",
        image:require('./assets/boneToy.webp'),
        desc:"Your pet will love this toy.",
        price:300,
        paws:4.5,
    },
    {
        id:4,
        name:"Dino Toy",
        image:require('./assets/dinoToy.jpg'),
        desc:"Your pet will love this toy.",
        price:500,
        paws:4.4,
    },
    {
        id:5,
        name:"Duck Toy",
        image:require('./assets/duckToy.jpg'),
        desc:"Your pet will love this toy.",
        price:500,
        paws:4.4,
    },
    {
        id:6,
        name:"Toy",
        image:require('./assets/someToy.jpg'),
        desc:"Your pet will love this toy.",
        price:250,
        paws:3.9,
    },
]

export const food = [
    {
        id:7,
        name:"Himalaya Pet Food",
        image:require('./assets/petFood1.jpg'),
        desc:"Your pet will love this Food.",
        price:1250,
        paws:4.3,
    },
    {
        id:8,
        name:"Canine Creek",
        image:require('./assets/petFood2.jpg'),
        desc:"Your pet will love this Food.",
        price:1050,
        paws:4.5,
    },
    {
        id:9,
        name:"Peanut Butter",
        image:require('./assets/petFood3.jpeg'),
        desc:"Your pet will love this Food.",
        price:950,
        paws:4.1,
    },
    {
        id:10,
        name:"Royal Pet Food",
        image:require('./assets/petFood4.jpg'),
        desc:"Your pet will love this Food.",
        price:2250,
        paws:4.6,
    },
]

export const vets = [
    {
        id:11,
        img:require('./assets/vet4.png'),
        name:"Paws & Whiskers Veterinary Clinic",
        address:"123 Pet Street Animalville, Imaginaryland 54321",
        contact:"234-567",
    },
    {
        id:12,
        img:require('./assets/vet3.png'),
        name:"Happy Tails Animal Hospital",
        address:"456 Tail Avenue Petropolis, Dreamland 98765",
        contact:"678-678",
    },
    {
        id:13,
        img:require('./assets/vet5.png'),
        name:"Furry Friends Veterinary Care",
        address:"789 Fur Lane Critterville, Fantasyland 24680",
        contact:"456-784",
    },
    {
        id:14,
        img:require('./assets/vet2.png'),
        name:"Whisker Haven Vet Center",
        address:"101 Whisker Way Kittyville, Wonderland 13579",
        contact:"234-578",
    },
    {
        id:15,
        img:require('./assets/vet1.png'),
        name:"Feathered Friends Bird Clinic",
        address:"222 Avian Avenue Birdtown, Imaginaria 86420",
        contact:"789-345",
    },
    {
        id:16,
        img:require('./assets/vet6.png'),
        name:"Exo-Scaly Creatures Vet Clinic",
        address:"333 Scales Street Reptilia City, Mythscape 70707",
        contact:"345-567",
    },

]